### ISSUE TITLE
xposed not working on Z3 LP  (alarmhook)

### ISSUE THREAD

**Issue by Eason85** [rsteckler/unbounce-android#114]
For some reason the xposed module isn't getting hooked by xposed. I've made sure SE is permissive and everything else seems to install and work fine, just not amplify. 

The error is java.lang.NoSuchMethodError: com.android.server.AlarmManagerService#triggerAlar msLocked(java.util.ArrayList,long,long)#extract

Thanks.

**Comment by mysiak** [comment]
Same with Z2 (permissive or enforcing), Xposed log here: http://textuploader.com/xv43

**Comment by rsteckler** [comment]
Should be fixed now.
