### ISSUE TITLE
Full name not scrolling

### ISSUE THREAD

**Issue by TheOTO** [rsteckler/unbounce-android#123]
The full name of the alarm/wakelock isn't scrolling anymore. I liked being able to see the full name.
Edit: Can see the full name when I click on alarm/wakelock in latest version.

**Comment by rsteckler** [comment]
This is now a setting.

**Comment by TheOTO** [comment]
Thanks man. When I posted that, I noticed that feature was back on the app
when I downloaded the beta. Btw, really liking the regex functions.
<https://www.avast.com/lp-safe-emailing?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/lp-safe-emailing?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
