### ISSUE TITLE
Unknown issue?

### ISSUE THREAD

**Issue by TheOTO** [rsteckler/unbounce-android#132]
I'm not sure this is really an issue or not but sometimes when I first open the app I see the donations at the bottom like I have the unpaid version. After a second it goes away. What I'm wondering is does this affect the wakelocks or alarms in any way?

**Comment by rsteckler** [comment]
Nope!  The donation check doesn't impact the part of the program that
actually does the blocking.

On Fri, Feb 19, 2016 at 6:54 AM TheOTO notifications@github.com wrote:

> I'm not sure this is really an issue or not but sometimes when I first
> open the app I see the donations at the bottom like I have the unpaid
> version. After a second it goes away. What I'm wondering is does this
> affect the wakelocks or alarms in any way?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rsteckler/unbounce-android/issues/132.
> 
> ## 

Thanks,
Ryan Steckler
