### ISSUE TITLE
Icing wake lock no longer safe to limit

### ISSUE THREAD

**Issue by briandotcom0** [rsteckler/unbounce-android#142]
After the new Google services update, it force closes Google services and chrome when it can't obtain the Icing wakelock.

**Comment by OswaldBoelcke** [comment]
I have limited **all** Google Play Services' related wakelocks and alarms including "Icing" and cannot recognise any negative impact on my device in its current configuration and the scenarios I use it (except for Play Store and the requirement of "low" localisation, no use of any Google related crap at all). Samsung S3 LTE (GT-I9305) with Resurrection Remix v5.7.4 Sammy and AGNi v4.5.5 pureCM kernel.

**Comment by briandotcom0** [comment]
I ran into something where all my google apps wouldn't work and that was the only fix I found, but in my new phone it works, so either something changed or I had something else causing the problem. Forgot to close this issue.
